import os
import random
import asyncio
import google.generativeai as genai
import edge_tts
import requests
from moviepy.editor import VideoFileClip, TextClip, CompositeVideoClip, AudioFileClip
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# CONFIGURATION
genai.configure(api_key=os.environ["GEMINI_KEY"])
PEXELS_API_KEY = os.environ["PEXELS_KEY"]

async def generate_content():
    print("1. Generating Script...")
    model = genai.GenerativeModel('gemini-1.5-flash')
    # You can change the topic here!
    prompt = "Write a shocking fun fact about history or science. Keep it under 25 words. No intro."
    response = model.generate_content(prompt)
    script = response.text.strip()
    print(f"Script: {script}")

    print("2. Generating Voice...")
    voice = "en-US-ChristopherNeural"
    communicate = edge_tts.Communicate(script, voice)
    await communicate.save("voice.mp3")

    print("3. Finding Video...")
    headers = {"Authorization": Pexels_API_KEY}
    query = random.choice(["technology", "ocean", "space", "abstract", "city"])
    url = f"https://api.pexels.com/videos/search?query={query}&per_page=1&orientation=portrait"
    r = requests.get(url, headers=headers)
    video_data = r.json()

    # Fallback if Pexels fails
    if not video_data.get('videos'):
        print("Pexels error, using fallback video logic needed.")
        return None

    video_url = video_data['videos'][0]['video_files'][0]['link']
    with open("background.mp4", "wb") as f:
        f.write(requests.get(video_url).content)

    return script

def edit_video(script_text):
    print("4. Editing Video...")
    if not script_text: return

    audio = AudioFileClip("voice.mp3")
    background = VideoFileClip("background.mp4")

    # Loop video if audio is longer
    if background.duration < audio.duration:
        background = background.loop(duration=audio.duration + 0.5)

    background = background.subclip(0, audio.duration).resize(height=1920)

    # Add Text Overlay (Centered)
    # Note: Size is set for 1080x1920 vertical video
    txt_clip = TextClip(script_text, fontsize=70, color='white', font='DejaVu-Sans-Bold', 
                       size=(800, None), method='caption', stroke_color='black', stroke_width=2)
    txt_clip = txt_clip.set_pos('center').set_duration(audio.duration)

    final = CompositeVideoClip([background, txt_clip]).set_audio(audio)
    final.write_videofile("short.mp4", fps=24, codec='libx264', audio_codec='aac')
    print("Video saved as short.mp4")

def upload_to_youtube(title):
    print("5. Uploading to YouTube...")
    creds = Credentials(
        None,
        refresh_token=os.environ["YT_REFRESH_TOKEN"],
        token_uri="https://oauth2.googleapis.com/token",
        client_id=os.environ["YT_CLIENT_ID"],
        client_secret=os.environ["YT_CLIENT_SECRET"]
    )

    youtube = build("youtube", "v3", credentials=creds)

    request = youtube.videos().insert(
        part="snippet,status",
        body={
            "snippet": {
                "title": f"{title} #shorts",
                "description": "Generated by AI",
                "tags": ["shorts", "facts", "ai"],
                "categoryId": "22"
            },
            "status": {
                "privacyStatus": "public" # Change to 'private' to test safely
            }
        },
        media_body=MediaFileUpload("short.mp4")
    )
    response = request.execute()
    print(f"Uploaded! Link: https://youtu.be/{response['id']}")

if __name__ == "__main__":
    script = asyncio.run(generate_content())
    if script:
        edit_video(script)
        upload_to_youtube("Did you know?")
